# Generated by Django 4.1 on 2022-08-10 04:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default=None, max_length=30)),
                ('occupation', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
                ('student_class', models.CharField(choices=[('First Grade', 'First Grade'), ('Second Grade', 'Second Grade'), ('Third Grade', 'Third Grade'), ('Fourth Grade', 'Fourth Grade'), ('Fifth Grade', 'Fifth Grade'), ('Sixth Grade', 'Sixth Grade'), ('Seventh Grade', 'Seventh Grade'), ('Eighth Grade', 'Eighth Grade')], default=None, max_length=25)),
                ('marks', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('father_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.studentdetailmodel')),
            ],
        ),
    ]
