# Generated by Django 4.1 on 2022-08-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_studentdetailmodel_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressmodel',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
